# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    # Example programs will be added here as we implement features
    #
    # obj = bld.create_ns3_program('ble-mesh-simple', ['ble-mesh-discovery'])
    # obj.source = 'ble-mesh-simple.cc'
    #
    # obj = bld.create_ns3_program('ble-mesh-clustering', ['ble-mesh-discovery'])
    # obj.source = 'ble-mesh-clustering.cc'
    #
    # obj = bld.create_ns3_program('ble-mesh-1000nodes', ['ble-mesh-discovery'])
    # obj.source = 'ble-mesh-1000nodes.cc'
    pass
